export const skills = [
  { name: 'AWS', displayName: 'AWS' },
  { name: 'GCP', displayName: 'Google Cloud' },
  { name: 'Kubernetes', displayName: 'Kubernetes' },
  { name: 'Lambda', displayName: 'AWS Lambda' },
  { name: 'Next.js', displayName: 'Next.js' },
  { name: 'Node.js', displayName: 'Node.js' },
  { name: 'React', displayName: 'React' },
  { name: 'TypeScript', displayName: 'TypeScript' },
  { name: 'Python', displayName: 'Python' },
  { name: 'Golang', displayName: 'Go' },
  { name: 'OpenAI', displayName: 'OpenAI' },
  { name: 'Anthropic', displayName: 'Claude' },
  { name: 'Gemini', displayName: 'Gemini' },
  { name: 'Vercel', displayName: 'Vercel' },
  { name: 'Neon', displayName: 'Neon DB' },
  { name: 'OpenClaw', displayName: 'OpenClaw' },
  { name: 'PostgreSQL', displayName: 'PostgreSQL' },
  { name: 'MongoDB', displayName: 'MongoDB' },
  { name: 'GraphQL', displayName: 'GraphQL' },
  { name: 'Docker', displayName: 'Docker' },
  { name: 'Tailwind', displayName: 'Tailwind CSS' },
];
